name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [10.x, 12.x]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node/Npm Versions
        run: |
          echo -n "Node: "
          node --version
          echo -n "NPM: "
          npm --version
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Flow Type Checking
        run: npx flow check
      - name: Test
        run: npm test -- --verbose
    artifacts:
      # expose_as: "Code Coverage"
      paths:
        - "coverage/"

